### ISSUE TITLE
G269 utilise IE comment bloquer IE en mag ? GIGIT

### ISSUE THREAD

**Issue by Grosjeanced** [darks54/0papier#9]

**Comment by MayouXIV** [comment]
Je refais une passe sur le mag pour remettre firefox par défaut.
Attention risque que le magasin fasse de nouveau la bascule...

**Comment by MayouXIV** [comment]
2 machines etaient revenu avec IE par défaut, la V1 et le POD A >> remis sur firefox

**Comment by darks54** [comment]
utiliser redirect.exe
